name: gradient_indicator_nav_bar
description: "custom gradient bottom navigation bar with indicator"
version: 0.0.3
homepage: https://github.com/juanmacUTP/gradient_indicator_nav_bar

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter: